name: custom_nested_scroll_view
description: A NestedScrollView that supports outer scroller to top overscroll.
version: 0.0.1
homepage: https://github.com/idootop/custom_nested_scroll_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.12.0-4.0.pre"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
